{{- if .Values.secret.externalSecret.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.secret.name }}
  labels:
    {{- include "warptalk.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-30"
    helm.sh/hook-delete-policy: before-hook-creation
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.secret.externalSecret.secretStoreName }}
  target:
    name: {{ .Values.secret.name }}
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: {{ .Values.secret.externalSecret.remoteKey }}
  data:
    - secretKey: PGUSER
      remoteRef:
        key: {{ .Values.secret.externalSecret.postgresRemoteKey }}
        property: username
    - secretKey: PGPASSWORD
      remoteRef:
        key: {{ .Values.secret.externalSecret.postgresRemoteKey }}
        property: password
    - secretKey: REDIS_PASSWORD
      remoteRef:
        key: {{ .Values.secret.externalSecret.redisRemoteKey }}
        property: password
    - secretKey: Redis__ConnectionString
      remoteRef:
        key: {{ .Values.secret.externalSecret.redisRemoteKey }}
        property: dotnet-connection-string
    - secretKey: ConnectionStrings__Redis
      remoteRef:
        key: {{ .Values.secret.externalSecret.redisRemoteKey }}
        property: dotnet-connection-string
    - secretKey: VECTOR_DB_API_KEY
      remoteRef:
        key: {{ .Values.secret.externalSecret.qdrantRemoteKey }}
        property: api-key
{{- end }}
