{{- range $name, $app := .Values.workloads }}
{{- if ge (int $app.replicas) 2 }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ $name }}
  labels:
    app.kubernetes.io/name: {{ $name }}
    {{- include "warptalk.labels" $ | nindent 4 }}
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ $name }}
{{- end }}
{{- end }}
