-- Demo seed, four companies — PART 1/4: auth (warptalk_auth). GENERATED by generate.py.
-- 36 accounts, password Password123, email pre-verified (demo logins, not real mailboxes).
\set ON_ERROR_STOP on
BEGIN;

CREATE TEMP TABLE demo_roster (
    user_id uuid PRIMARY KEY, email text NOT NULL, full_name text NOT NULL,
    preferred_language text NOT NULL, speak_language text NOT NULL, listen_language text NOT NULL
) ON COMMIT DROP;
INSERT INTO demo_roster VALUES
    ('019f2b00-0de0-7000-9300-000000000101', 'ngonhi@lumoralogistics.vn', 'Ngô Xuân Hạnh Nhi', 'vi-VN', 'vi-VN', 'en-US'),
    ('019f2b00-0de0-7000-9300-000000000102', 'manhtuan@lumoralogistics.vn', 'Trần Mạnh Tuấn', 'en-US', 'en-US', 'vi-VN'),
    ('019f2b00-0de0-7000-9300-000000000103', 'ngocky@lumoralogistics.vn', 'Huỳnh Ngọc Kỳ', 'vi-VN', 'vi-VN', 'en-US'),
    ('019f2b00-0de0-7000-9300-000000000104', 'tuhuynh@lumoralogistics.vn', 'Huỳnh Thái Tú', 'vi-VN', 'vi-VN', 'en-US'),
    ('019f2b00-0de0-7000-9300-000000000105', 'thanhhuong@lumoralogistics.vn', 'Nguyễn Thanh Hương', 'en-US', 'en-US', 'vi-VN'),
    ('019f2b00-0de0-7000-9300-000000000106', 'quocbao@lumoralogistics.vn', 'Lê Quốc Bảo', 'vi-VN', 'vi-VN', 'en-US'),
    ('019f2b00-0de0-7000-9300-000000000107', 'minhanh@lumoralogistics.vn', 'Phạm Minh Anh', 'en-US', 'en-US', 'vi-VN'),
    ('019f2b00-0de0-7000-9300-000000000108', 'ducthang@lumoralogistics.vn', 'Võ Đức Thắng', 'vi-VN', 'vi-VN', 'en-US'),
    ('019f2b00-0de0-7000-9300-000000000109', 'lanphuong@lumoralogistics.vn', 'Đặng Lan Phương', 'en-US', 'en-US', 'vi-VN'),
    ('019f2b00-0de0-7000-9300-000000000201', 'ngonhi@kestrelfintech.vn', 'Ngô Xuân Hạnh Nhi', 'vi-VN', 'vi-VN', 'en-US'),
    ('019f2b00-0de0-7000-9300-000000000202', 'manhtuan@kestrelfintech.vn', 'Trần Mạnh Tuấn', 'en-US', 'en-US', 'vi-VN'),
    ('019f2b00-0de0-7000-9300-000000000203', 'ngocky@kestrelfintech.vn', 'Huỳnh Ngọc Kỳ', 'vi-VN', 'vi-VN', 'en-US'),
    ('019f2b00-0de0-7000-9300-000000000204', 'tuhuynh@kestrelfintech.vn', 'Huỳnh Thái Tú', 'vi-VN', 'vi-VN', 'en-US'),
    ('019f2b00-0de0-7000-9300-000000000205', 'thanhhuong@kestrelfintech.vn', 'Nguyễn Thanh Hương', 'en-US', 'en-US', 'vi-VN'),
    ('019f2b00-0de0-7000-9300-000000000206', 'quocbao@kestrelfintech.vn', 'Lê Quốc Bảo', 'vi-VN', 'vi-VN', 'en-US'),
    ('019f2b00-0de0-7000-9300-000000000207', 'minhanh@kestrelfintech.vn', 'Phạm Minh Anh', 'en-US', 'en-US', 'vi-VN'),
    ('019f2b00-0de0-7000-9300-000000000208', 'ducthang@kestrelfintech.vn', 'Võ Đức Thắng', 'vi-VN', 'vi-VN', 'en-US'),
    ('019f2b00-0de0-7000-9300-000000000209', 'lanphuong@kestrelfintech.vn', 'Đặng Lan Phương', 'en-US', 'en-US', 'vi-VN'),
    ('019f2b00-0de0-7000-9300-000000000301', 'ngonhi@aurionpharma.vn', 'Ngô Xuân Hạnh Nhi', 'vi-VN', 'vi-VN', 'en-US'),
    ('019f2b00-0de0-7000-9300-000000000302', 'manhtuan@aurionpharma.vn', 'Trần Mạnh Tuấn', 'en-US', 'en-US', 'vi-VN'),
    ('019f2b00-0de0-7000-9300-000000000303', 'ngocky@aurionpharma.vn', 'Huỳnh Ngọc Kỳ', 'vi-VN', 'vi-VN', 'en-US'),
    ('019f2b00-0de0-7000-9300-000000000304', 'tuhuynh@aurionpharma.vn', 'Huỳnh Thái Tú', 'vi-VN', 'vi-VN', 'en-US'),
    ('019f2b00-0de0-7000-9300-000000000305', 'thanhhuong@aurionpharma.vn', 'Nguyễn Thanh Hương', 'en-US', 'en-US', 'vi-VN'),
    ('019f2b00-0de0-7000-9300-000000000306', 'quocbao@aurionpharma.vn', 'Lê Quốc Bảo', 'vi-VN', 'vi-VN', 'en-US'),
    ('019f2b00-0de0-7000-9300-000000000307', 'minhanh@aurionpharma.vn', 'Phạm Minh Anh', 'en-US', 'en-US', 'vi-VN'),
    ('019f2b00-0de0-7000-9300-000000000308', 'ducthang@aurionpharma.vn', 'Võ Đức Thắng', 'vi-VN', 'vi-VN', 'en-US'),
    ('019f2b00-0de0-7000-9300-000000000309', 'lanphuong@aurionpharma.vn', 'Đặng Lan Phương', 'en-US', 'en-US', 'vi-VN'),
    ('019f2b00-0de0-7000-9300-000000000401', 'ngonhi@tidewellretail.vn', 'Ngô Xuân Hạnh Nhi', 'vi-VN', 'vi-VN', 'en-US'),
    ('019f2b00-0de0-7000-9300-000000000402', 'manhtuan@tidewellretail.vn', 'Trần Mạnh Tuấn', 'en-US', 'en-US', 'vi-VN'),
    ('019f2b00-0de0-7000-9300-000000000403', 'ngocky@tidewellretail.vn', 'Huỳnh Ngọc Kỳ', 'vi-VN', 'vi-VN', 'en-US'),
    ('019f2b00-0de0-7000-9300-000000000404', 'tuhuynh@tidewellretail.vn', 'Huỳnh Thái Tú', 'vi-VN', 'vi-VN', 'en-US'),
    ('019f2b00-0de0-7000-9300-000000000405', 'thanhhuong@tidewellretail.vn', 'Nguyễn Thanh Hương', 'en-US', 'en-US', 'vi-VN'),
    ('019f2b00-0de0-7000-9300-000000000406', 'quocbao@tidewellretail.vn', 'Lê Quốc Bảo', 'vi-VN', 'vi-VN', 'en-US'),
    ('019f2b00-0de0-7000-9300-000000000407', 'minhanh@tidewellretail.vn', 'Phạm Minh Anh', 'en-US', 'en-US', 'vi-VN'),
    ('019f2b00-0de0-7000-9300-000000000408', 'ducthang@tidewellretail.vn', 'Võ Đức Thắng', 'vi-VN', 'vi-VN', 'en-US'),
    ('019f2b00-0de0-7000-9300-000000000409', 'lanphuong@tidewellretail.vn', 'Đặng Lan Phương', 'en-US', 'en-US', 'vi-VN');

INSERT INTO auth.users (
    id, email, password_hash, full_name, preferred_language, timezone,
    is_active, is_locked, email_verified, email_verified_at, created_at, updated_at
)
SELECT r.user_id, r.email, 'v2$SHA512$100000$16$jTFWzSKOXyuo/xZ+StGHwQ==$77jDm7DDcuTF57fhqikvLFBJhjrwoGuni8WcPdOhpAc=', r.full_name, r.preferred_language, 'Asia/Ho_Chi_Minh',
       true, false, true, NOW(), NOW(), NOW()
FROM demo_roster AS r
ON CONFLICT (email) DO UPDATE SET full_name = EXCLUDED.full_name, is_active = true, is_locked = false;

-- An email that already belonged to another account would leave PART 2 pointing at a user id that
-- does not exist. Fail here instead of half-seeding.
DO $$
DECLARE v_conflict text;
BEGIN
    SELECT string_agg(u.email, ', ') INTO v_conflict
    FROM demo_roster AS r JOIN auth.users AS u ON lower(u.email) = lower(r.email)
    WHERE u.id <> r.user_id;
    IF v_conflict IS NOT NULL THEN
        RAISE EXCEPTION 'Email already used by another account: %', v_conflict;
    END IF;
END $$;

INSERT INTO auth.user_settings (
    id, user_id, default_speak_language, default_listen_language,
    voice_clone_enabled, auto_generate_summary, default_max_participants, updated_at
)
SELECT gen_random_uuid(), r.user_id, r.speak_language, r.listen_language, true, true, 10, NOW()
FROM demo_roster AS r
ON CONFLICT (user_id) DO UPDATE SET
    default_speak_language = EXCLUDED.default_speak_language,
    default_listen_language = EXCLUDED.default_listen_language,
    voice_clone_enabled = true, auto_generate_summary = true, updated_at = NOW();

-- Platform role 'user' only: these logins must not reach /api/v1/admin/*.
INSERT INTO auth.user_roles (id, user_id, role_id, assigned_at)
SELECT gen_random_uuid(), r.user_id, sys.id, NOW()
FROM demo_roster AS r CROSS JOIN (SELECT id FROM auth.roles WHERE name = 'user') AS sys
WHERE NOT EXISTS (SELECT 1 FROM auth.user_roles ur WHERE ur.user_id = r.user_id AND ur.role_id = sys.id);

DO $$
DECLARE v int;
BEGIN
    SELECT count(*) INTO v FROM auth.users
    WHERE id::text LIKE '019f2b00-0de0-7000-9300-%' AND is_active AND email_verified;
    IF v <> 36 THEN RAISE EXCEPTION 'Expected 36 demo accounts, found %', v; END IF;
END $$;

COMMIT;
