-- Demo seed, four companies — PART 2/4: workspace (warptalk_workspace). GENERATED by generate.py.
-- Run PART 1 first. Flow 1 workspaces get their Owner only; Flow 2 workspaces get all nine.
\set ON_ERROR_STOP on
BEGIN;

-- Lumora Logistics (f1-main, Flow 1)
INSERT INTO workspace.workspaces (
    id, name, slug, owner_id, logo_url, allow_external_collaboration,
    require_verified_domain_for_internal, allow_subdomains, settings, is_active,
    created_at, created_by, updated_at, updated_by
) VALUES (
    '019f2b00-0de0-7000-9300-0000000000a1', 'Lumora Logistics', 'lumora-logistics', '019f2b00-0de0-7000-9300-000000000101', NULL, true, false, false,
    jsonb_build_object(
        'DefaultLanguage', 'vi', 'Timezone', 'Asia/Ho_Chi_Minh', 'MaxActiveRooms', 20,
        'ArtifactRetentionDays', 30, 'InvitationExpiryDays', 7, 'VoiceCloningEnabled', true,
        'IsProfanityFilterEnabled', true, 'RestrictLanguages', true, 'AllowAnyPlugins', true,
        'AllowedTargetLanguages', jsonb_build_array('vi', 'en', 'ja'),
        'VerifiedDomains', jsonb_build_array('lumoralogistics.vn'),
        'AllowExternalCollaboration', true, 'RequireVerifiedDomainForInternal', false,
        'ExternalGracePeriodHours', NULL,
        'AiUsagePolicy', jsonb_build_object(
            'AllowExternalLlm', true, 'UseGlobalGlossary', true,
            'RedactPii', jsonb_build_object('Enabled', true),
            'Dlp', jsonb_build_object('Enabled', true, 'KeywordsBlacklist', jsonb_build_array('Fuck', 'Shit', 'Damn')),
            'TranslationProfile', jsonb_build_object(
                'TranslationTone', 'professional',
                'LanguageSpecificRules', jsonb_build_object(
                    'VietnameseHonorificStyle', 'formal_hierarchical',
                    'JapaneseHonorificStyle', 'keigo_teineigo')))),
    true, NOW(), '019f2b00-0de0-7000-9300-000000000101', NOW(), '019f2b00-0de0-7000-9300-000000000101'
)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, slug = EXCLUDED.slug, owner_id = EXCLUDED.owner_id,
    settings = EXCLUDED.settings, is_active = true, deleted_at = NULL, deleted_by = NULL, updated_at = NOW();
-- Kestrel Fintech (f1-backup, Flow 1)
INSERT INTO workspace.workspaces (
    id, name, slug, owner_id, logo_url, allow_external_collaboration,
    require_verified_domain_for_internal, allow_subdomains, settings, is_active,
    created_at, created_by, updated_at, updated_by
) VALUES (
    '019f2b00-0de0-7000-9300-0000000000a2', 'Kestrel Fintech', 'kestrel-fintech', '019f2b00-0de0-7000-9300-000000000201', NULL, true, false, false,
    jsonb_build_object(
        'DefaultLanguage', 'vi', 'Timezone', 'Asia/Ho_Chi_Minh', 'MaxActiveRooms', 20,
        'ArtifactRetentionDays', 30, 'InvitationExpiryDays', 7, 'VoiceCloningEnabled', true,
        'IsProfanityFilterEnabled', true, 'RestrictLanguages', true, 'AllowAnyPlugins', true,
        'AllowedTargetLanguages', jsonb_build_array('vi', 'en', 'ja'),
        'VerifiedDomains', jsonb_build_array('kestrelfintech.vn'),
        'AllowExternalCollaboration', true, 'RequireVerifiedDomainForInternal', false,
        'ExternalGracePeriodHours', NULL,
        'AiUsagePolicy', jsonb_build_object(
            'AllowExternalLlm', true, 'UseGlobalGlossary', true,
            'RedactPii', jsonb_build_object('Enabled', true),
            'Dlp', jsonb_build_object('Enabled', true, 'KeywordsBlacklist', jsonb_build_array('Fuck', 'Shit', 'Damn')),
            'TranslationProfile', jsonb_build_object(
                'TranslationTone', 'professional',
                'LanguageSpecificRules', jsonb_build_object(
                    'VietnameseHonorificStyle', 'formal_hierarchical',
                    'JapaneseHonorificStyle', 'keigo_teineigo')))),
    true, NOW(), '019f2b00-0de0-7000-9300-000000000201', NOW(), '019f2b00-0de0-7000-9300-000000000201'
)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, slug = EXCLUDED.slug, owner_id = EXCLUDED.owner_id,
    settings = EXCLUDED.settings, is_active = true, deleted_at = NULL, deleted_by = NULL, updated_at = NOW();
-- Aurion Pharma (f2-main, Flow 2)
INSERT INTO workspace.workspaces (
    id, name, slug, owner_id, logo_url, allow_external_collaboration,
    require_verified_domain_for_internal, allow_subdomains, settings, is_active,
    created_at, created_by, updated_at, updated_by
) VALUES (
    '019f2b00-0de0-7000-9300-0000000000a3', 'Aurion Pharma', 'aurion-pharma', '019f2b00-0de0-7000-9300-000000000301', NULL, true, false, false,
    jsonb_build_object(
        'DefaultLanguage', 'vi', 'Timezone', 'Asia/Ho_Chi_Minh', 'MaxActiveRooms', 20,
        'ArtifactRetentionDays', 30, 'InvitationExpiryDays', 7, 'VoiceCloningEnabled', true,
        'IsProfanityFilterEnabled', true, 'RestrictLanguages', true, 'AllowAnyPlugins', true,
        'AllowedTargetLanguages', jsonb_build_array('vi', 'en', 'ja'),
        'VerifiedDomains', jsonb_build_array('aurionpharma.vn'),
        'AllowExternalCollaboration', true, 'RequireVerifiedDomainForInternal', false,
        'ExternalGracePeriodHours', NULL,
        'AiUsagePolicy', jsonb_build_object(
            'AllowExternalLlm', true, 'UseGlobalGlossary', true,
            'RedactPii', jsonb_build_object('Enabled', true),
            'Dlp', jsonb_build_object('Enabled', true, 'KeywordsBlacklist', jsonb_build_array('Fuck', 'Shit', 'Damn')),
            'TranslationProfile', jsonb_build_object(
                'TranslationTone', 'professional',
                'LanguageSpecificRules', jsonb_build_object(
                    'VietnameseHonorificStyle', 'formal_hierarchical',
                    'JapaneseHonorificStyle', 'keigo_teineigo')))),
    true, NOW(), '019f2b00-0de0-7000-9300-000000000301', NOW(), '019f2b00-0de0-7000-9300-000000000301'
)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, slug = EXCLUDED.slug, owner_id = EXCLUDED.owner_id,
    settings = EXCLUDED.settings, is_active = true, deleted_at = NULL, deleted_by = NULL, updated_at = NOW();
-- Tidewell Retail (f2-backup, Flow 2)
INSERT INTO workspace.workspaces (
    id, name, slug, owner_id, logo_url, allow_external_collaboration,
    require_verified_domain_for_internal, allow_subdomains, settings, is_active,
    created_at, created_by, updated_at, updated_by
) VALUES (
    '019f2b00-0de0-7000-9300-0000000000a4', 'Tidewell Retail', 'tidewell-retail', '019f2b00-0de0-7000-9300-000000000401', NULL, true, false, false,
    jsonb_build_object(
        'DefaultLanguage', 'vi', 'Timezone', 'Asia/Ho_Chi_Minh', 'MaxActiveRooms', 20,
        'ArtifactRetentionDays', 30, 'InvitationExpiryDays', 7, 'VoiceCloningEnabled', true,
        'IsProfanityFilterEnabled', true, 'RestrictLanguages', true, 'AllowAnyPlugins', true,
        'AllowedTargetLanguages', jsonb_build_array('vi', 'en', 'ja'),
        'VerifiedDomains', jsonb_build_array('tidewellretail.vn'),
        'AllowExternalCollaboration', true, 'RequireVerifiedDomainForInternal', false,
        'ExternalGracePeriodHours', NULL,
        'AiUsagePolicy', jsonb_build_object(
            'AllowExternalLlm', true, 'UseGlobalGlossary', true,
            'RedactPii', jsonb_build_object('Enabled', true),
            'Dlp', jsonb_build_object('Enabled', true, 'KeywordsBlacklist', jsonb_build_array('Fuck', 'Shit', 'Damn')),
            'TranslationProfile', jsonb_build_object(
                'TranslationTone', 'professional',
                'LanguageSpecificRules', jsonb_build_object(
                    'VietnameseHonorificStyle', 'formal_hierarchical',
                    'JapaneseHonorificStyle', 'keigo_teineigo')))),
    true, NOW(), '019f2b00-0de0-7000-9300-000000000401', NOW(), '019f2b00-0de0-7000-9300-000000000401'
)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, slug = EXCLUDED.slug, owner_id = EXCLUDED.owner_id,
    settings = EXCLUDED.settings, is_active = true, deleted_at = NULL, deleted_by = NULL, updated_at = NOW();

CREATE TEMP TABLE demo_members (workspace_id uuid, user_id uuid, role_id uuid) ON COMMIT DROP;
INSERT INTO demo_members VALUES
    ('019f2b00-0de0-7000-9300-0000000000a1', '019f2b00-0de0-7000-9300-000000000101', '6ed77306-70aa-4ece-a00e-30dd3763035a'),
    ('019f2b00-0de0-7000-9300-0000000000a2', '019f2b00-0de0-7000-9300-000000000201', '6ed77306-70aa-4ece-a00e-30dd3763035a'),
    ('019f2b00-0de0-7000-9300-0000000000a3', '019f2b00-0de0-7000-9300-000000000301', '6ed77306-70aa-4ece-a00e-30dd3763035a'),
    ('019f2b00-0de0-7000-9300-0000000000a3', '019f2b00-0de0-7000-9300-000000000302', 'a737aee0-9423-4dd7-8809-8e898f4b5317'),
    ('019f2b00-0de0-7000-9300-0000000000a3', '019f2b00-0de0-7000-9300-000000000303', 'a737aee0-9423-4dd7-8809-8e898f4b5317'),
    ('019f2b00-0de0-7000-9300-0000000000a3', '019f2b00-0de0-7000-9300-000000000304', 'fdb38f47-1191-4730-a3d9-eade73a75527'),
    ('019f2b00-0de0-7000-9300-0000000000a3', '019f2b00-0de0-7000-9300-000000000305', 'a737aee0-9423-4dd7-8809-8e898f4b5317'),
    ('019f2b00-0de0-7000-9300-0000000000a3', '019f2b00-0de0-7000-9300-000000000306', 'a737aee0-9423-4dd7-8809-8e898f4b5317'),
    ('019f2b00-0de0-7000-9300-0000000000a3', '019f2b00-0de0-7000-9300-000000000307', 'fdb38f47-1191-4730-a3d9-eade73a75527'),
    ('019f2b00-0de0-7000-9300-0000000000a3', '019f2b00-0de0-7000-9300-000000000308', 'fdb38f47-1191-4730-a3d9-eade73a75527'),
    ('019f2b00-0de0-7000-9300-0000000000a3', '019f2b00-0de0-7000-9300-000000000309', 'fdb38f47-1191-4730-a3d9-eade73a75527'),
    ('019f2b00-0de0-7000-9300-0000000000a4', '019f2b00-0de0-7000-9300-000000000401', '6ed77306-70aa-4ece-a00e-30dd3763035a'),
    ('019f2b00-0de0-7000-9300-0000000000a4', '019f2b00-0de0-7000-9300-000000000402', 'a737aee0-9423-4dd7-8809-8e898f4b5317'),
    ('019f2b00-0de0-7000-9300-0000000000a4', '019f2b00-0de0-7000-9300-000000000403', 'a737aee0-9423-4dd7-8809-8e898f4b5317'),
    ('019f2b00-0de0-7000-9300-0000000000a4', '019f2b00-0de0-7000-9300-000000000404', 'fdb38f47-1191-4730-a3d9-eade73a75527'),
    ('019f2b00-0de0-7000-9300-0000000000a4', '019f2b00-0de0-7000-9300-000000000405', 'a737aee0-9423-4dd7-8809-8e898f4b5317'),
    ('019f2b00-0de0-7000-9300-0000000000a4', '019f2b00-0de0-7000-9300-000000000406', 'a737aee0-9423-4dd7-8809-8e898f4b5317'),
    ('019f2b00-0de0-7000-9300-0000000000a4', '019f2b00-0de0-7000-9300-000000000407', 'fdb38f47-1191-4730-a3d9-eade73a75527'),
    ('019f2b00-0de0-7000-9300-0000000000a4', '019f2b00-0de0-7000-9300-000000000408', 'fdb38f47-1191-4730-a3d9-eade73a75527'),
    ('019f2b00-0de0-7000-9300-0000000000a4', '019f2b00-0de0-7000-9300-000000000409', 'fdb38f47-1191-4730-a3d9-eade73a75527');

INSERT INTO workspace.workspace_members (
    id, workspace_id, user_id, role_id, membership_type, status, can_create_meetings, joined_at
)
SELECT gen_random_uuid(), m.workspace_id, m.user_id, m.role_id, 'Internal', 'active', true, NOW()
FROM demo_members AS m
ON CONFLICT (workspace_id, user_id) DO UPDATE SET
    role_id = EXCLUDED.role_id, membership_type = 'Internal', status = 'active',
    can_create_meetings = true, removed_at = NULL, removed_by = NULL;

DO $$
DECLARE v int; v_roles int;
BEGIN
    SELECT count(*) INTO v FROM workspace.workspace_members
    WHERE workspace_id::text LIKE '019f2b00-0de0-7000-9300-%' AND status = 'active' AND removed_at IS NULL;
    IF v <> 20 THEN RAISE EXCEPTION 'Expected 20 demo memberships, found %', v; END IF;
    SELECT count(*) INTO v_roles FROM (VALUES ('6ed77306-70aa-4ece-a00e-30dd3763035a'::uuid), ('a737aee0-9423-4dd7-8809-8e898f4b5317'::uuid), ('fdb38f47-1191-4730-a3d9-eade73a75527'::uuid)) AS r(id)
    WHERE r.id IN (SELECT role_id FROM workspace.workspace_members WHERE workspace_id::text LIKE '019f2b00-0de0-7000-9300-%');
    IF v_roles <> 3 THEN RAISE EXCEPTION 'Owner/Admin/Member role ids did not all land; re-check ROLE_IDS'; END IF;
END $$;

COMMIT;
