-- Demo seed, four companies — PART 3/4: billing (warptalk_billing). GENERATED by generate.py.
-- A live subscription per workspace on the `enterprise` plan, the plan the main demo workspace
-- runs on (no longer for sale, still honoured). Without it WT-515's paywall blocks meetings.
-- The entitlement snapshot is NOT written here: EntitlementReconcileWorker republishes it from
-- these rows within its interval (hourly). Never hand-write workspace_entitlement_snapshots.
\set ON_ERROR_STOP on
BEGIN;

CREATE TEMP TABLE demo_plan AS
SELECT id FROM subscription.plans WHERE slug = 'enterprise' AND deleted_at IS NULL LIMIT 1;
DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM demo_plan) THEN RAISE EXCEPTION 'No enterprise plan'; END IF;
END $$;

INSERT INTO subscription.subscriptions (
    id, user_id, workspace_id, plan_id, status, credits_remaining, credits_used_this_cycle,
    overage_credits_this_cycle, current_period_start, current_period_end, auto_renew, is_active,
    service_state, owner_email_domain, billing_contact_email, created_at, created_by, updated_at, updated_by
)
SELECT '019f2b00-0de0-7000-9300-0000000000b1', '019f2b00-0de0-7000-9300-000000000101', '019f2b00-0de0-7000-9300-0000000000a1', p.id, 'active', 1400000, 0, 0,
       NOW() - INTERVAL '1 day', NOW() + INTERVAL '30 days', true, true, 'healthy',
       'lumoralogistics.vn', 'ngonhi@lumoralogistics.vn', NOW(), '019f2b00-0de0-7000-9300-000000000101', NOW(), '019f2b00-0de0-7000-9300-000000000101'
FROM demo_plan AS p
ON CONFLICT (id) DO UPDATE SET
    plan_id = EXCLUDED.plan_id, status = 'active', is_active = true, service_state = 'healthy',
    credits_remaining = EXCLUDED.credits_remaining, current_period_start = EXCLUDED.current_period_start,
    current_period_end = EXCLUDED.current_period_end, deleted_at = NULL, updated_at = NOW();
INSERT INTO subscription.subscriptions (
    id, user_id, workspace_id, plan_id, status, credits_remaining, credits_used_this_cycle,
    overage_credits_this_cycle, current_period_start, current_period_end, auto_renew, is_active,
    service_state, owner_email_domain, billing_contact_email, created_at, created_by, updated_at, updated_by
)
SELECT '019f2b00-0de0-7000-9300-0000000000b2', '019f2b00-0de0-7000-9300-000000000201', '019f2b00-0de0-7000-9300-0000000000a2', p.id, 'active', 1400000, 0, 0,
       NOW() - INTERVAL '1 day', NOW() + INTERVAL '30 days', true, true, 'healthy',
       'kestrelfintech.vn', 'ngonhi@kestrelfintech.vn', NOW(), '019f2b00-0de0-7000-9300-000000000201', NOW(), '019f2b00-0de0-7000-9300-000000000201'
FROM demo_plan AS p
ON CONFLICT (id) DO UPDATE SET
    plan_id = EXCLUDED.plan_id, status = 'active', is_active = true, service_state = 'healthy',
    credits_remaining = EXCLUDED.credits_remaining, current_period_start = EXCLUDED.current_period_start,
    current_period_end = EXCLUDED.current_period_end, deleted_at = NULL, updated_at = NOW();
INSERT INTO subscription.subscriptions (
    id, user_id, workspace_id, plan_id, status, credits_remaining, credits_used_this_cycle,
    overage_credits_this_cycle, current_period_start, current_period_end, auto_renew, is_active,
    service_state, owner_email_domain, billing_contact_email, created_at, created_by, updated_at, updated_by
)
SELECT '019f2b00-0de0-7000-9300-0000000000b3', '019f2b00-0de0-7000-9300-000000000301', '019f2b00-0de0-7000-9300-0000000000a3', p.id, 'active', 1400000, 0, 0,
       NOW() - INTERVAL '1 day', NOW() + INTERVAL '30 days', true, true, 'healthy',
       'aurionpharma.vn', 'ngonhi@aurionpharma.vn', NOW(), '019f2b00-0de0-7000-9300-000000000301', NOW(), '019f2b00-0de0-7000-9300-000000000301'
FROM demo_plan AS p
ON CONFLICT (id) DO UPDATE SET
    plan_id = EXCLUDED.plan_id, status = 'active', is_active = true, service_state = 'healthy',
    credits_remaining = EXCLUDED.credits_remaining, current_period_start = EXCLUDED.current_period_start,
    current_period_end = EXCLUDED.current_period_end, deleted_at = NULL, updated_at = NOW();
INSERT INTO subscription.subscriptions (
    id, user_id, workspace_id, plan_id, status, credits_remaining, credits_used_this_cycle,
    overage_credits_this_cycle, current_period_start, current_period_end, auto_renew, is_active,
    service_state, owner_email_domain, billing_contact_email, created_at, created_by, updated_at, updated_by
)
SELECT '019f2b00-0de0-7000-9300-0000000000b4', '019f2b00-0de0-7000-9300-000000000401', '019f2b00-0de0-7000-9300-0000000000a4', p.id, 'active', 1400000, 0, 0,
       NOW() - INTERVAL '1 day', NOW() + INTERVAL '30 days', true, true, 'healthy',
       'tidewellretail.vn', 'ngonhi@tidewellretail.vn', NOW(), '019f2b00-0de0-7000-9300-000000000401', NOW(), '019f2b00-0de0-7000-9300-000000000401'
FROM demo_plan AS p
ON CONFLICT (id) DO UPDATE SET
    plan_id = EXCLUDED.plan_id, status = 'active', is_active = true, service_state = 'healthy',
    credits_remaining = EXCLUDED.credits_remaining, current_period_start = EXCLUDED.current_period_start,
    current_period_end = EXCLUDED.current_period_end, deleted_at = NULL, updated_at = NOW();

DO $$
DECLARE v int;
BEGIN
    SELECT count(*) INTO v FROM subscription.subscriptions
    WHERE workspace_id::text LIKE '019f2b00-0de0-7000-9300-%'
      AND is_active AND status = 'active' AND current_period_end >= NOW() AND deleted_at IS NULL;
    IF v <> 4 THEN RAISE EXCEPTION 'Expected 4 live subscriptions, found %', v; END IF;
END $$;

COMMIT;
