#!/usr/bin/env python3
"""Generate the SQL for the four demo workspaces (Flow 1 and Flow 2, each a main and a backup).

WHY GENERATED
    Four workspaces x nine people is 36 accounts whose emails, names, roles and ids must agree
    across four databases (auth, workspace, billing, transcript) that no single transaction spans.
    One roster here, four SQL files out, so a typo cannot make one database disagree with another.

WHAT EACH WORKSPACE GETS
    Flow 1 (main, backup)  — empty: only the Owner is a member. The other eight accounts exist and
                             can log in, but are NOT invited: Flow 1 invites them on stage.
    Flow 2 (main, backup)  — what Flow 1 leaves behind: all nine are members with their roles, a
                             glossary in each direction, and the Settings Flow 1 walks through.
    All four               — a live subscription on the `enterprise` plan, the same one the main
                             demo workspace runs on. Without it the WT-515 paywall blocks meetings.

    Each company has its OWN name and its OWN email domain. The list this replaces put four
    look-alike workspaces ("AIBuilding Company", "…CompanyX", "…Company File") on one domain.

NOT SEEDED (do these in the UI, see README.md)
    Documents (they need real files in object storage and the indexing pipeline), voice-clone
    consent (a person's own biometric consent), and the entitlement snapshot — billing's hourly
    EntitlementReconcileWorker republishes it from the subscription; do not hand-write it.

Usage:  python3 generate.py   (writes 01-auth.sql … 04-glossary.sql next to this file)
"""

from __future__ import annotations

import csv
from pathlib import Path

HERE = Path(__file__).resolve().parent
DEMO_DIR = HERE.parent.parent / "demo"
ID = "019f2b00-0de0-7000-9300-{:012x}".format

# Same PBKDF2-SHA512 hash as every other WarpTalk seed: Password123.
# VoiceConsentTextVersions.Current in the auth service (read 4 Oct 2026).
VOICE_CONSENT_VERSION = "2026-09-29.v2"

PASSWORD_HASH = "v2$SHA512$100000$16$jTFWzSKOXyuo/xZ+StGHwQ==$77jDm7DDcuTF57fhqikvLFBJhjrwoGuni8WcPdOhpAc="

# Live production role ids (auth.roles), read 4 Oct 2026. Asserted in 02-workspace.sql.
ROLE_IDS = {
    "Owner": "6ed77306-70aa-4ece-a00e-30dd3763035a",
    "Admin": "a737aee0-9423-4dd7-8809-8e898f4b5317",
    "Member": "fdb38f47-1191-4730-a3d9-eade73a75527",
}

# (local part, full name, speak, listen, Flow 2 role). Speak/listen alternate so a meeting always
# has someone to translate for — with one shared language the pipeline has nothing to do.
PEOPLE = [
    ("ngonhi", "Ngô Xuân Hạnh Nhi", "vi-VN", "en-US", "Owner"),
    ("manhtuan", "Trần Mạnh Tuấn", "en-US", "vi-VN", "Admin"),
    ("ngocky", "Huỳnh Ngọc Kỳ", "vi-VN", "en-US", "Admin"),
    ("tuhuynh", "Huỳnh Thái Tú", "vi-VN", "en-US", "Member"),
    ("thanhhuong", "Nguyễn Thanh Hương", "en-US", "vi-VN", "Admin"),
    ("quocbao", "Lê Quốc Bảo", "vi-VN", "en-US", "Admin"),
    ("minhanh", "Phạm Minh Anh", "en-US", "vi-VN", "Member"),
    ("ducthang", "Võ Đức Thắng", "vi-VN", "en-US", "Member"),
    ("lanphuong", "Đặng Lan Phương", "en-US", "vi-VN", "Member"),
]

# (key, company, slug, domain, flow). Fictional companies, one domain each.
WORKSPACES = [
    ("f1-main", "Lumora Logistics", "lumora-logistics", "lumoralogistics.vn", 1),
    ("f1-backup", "Kestrel Fintech", "kestrel-fintech", "kestrelfintech.vn", 1),
    ("f2-main", "Aurion Pharma", "aurion-pharma", "aurionpharma.vn", 2),
    ("f2-backup", "Tidewell Retail", "tidewell-retail", "tidewellretail.vn", 2),
]


def q(text: str | None) -> str:
    return "NULL" if text is None else "'" + text.replace("'", "''") + "'"


def user_id(ws_index: int, person_index: int) -> str:
    return ID(0x100 * (ws_index + 1) + person_index + 1)


def workspace_id(ws_index: int) -> str:
    return ID(0xA0 + ws_index + 1)


def roster() -> list[dict]:
    rows = []
    for w, (key, company, slug, domain, flow) in enumerate(WORKSPACES):
        for p, (local, name, speak, listen, role) in enumerate(PEOPLE):
            rows.append(
                dict(ws=w, key=key, company=company, slug=slug, domain=domain, flow=flow,
                     user_id=user_id(w, p), email=f"{local}@{domain}", name=name,
                     speak=speak, listen=listen, role=role, owner=p == 0)
            )
    return rows


def auth_sql(rows: list[dict]) -> str:
    values = ",\n".join(
        f"    ({q(r['user_id'])}, {q(r['email'])}, {q(r['name'])}, {q(r['speak'])}, {q(r['speak'])}, {q(r['listen'])})"
        for r in rows
    )
    return f"""-- Demo seed, four companies — PART 1/4: auth (warptalk_auth). GENERATED by generate.py.
-- {len(rows)} accounts, password Password123, email pre-verified (demo logins, not real mailboxes).
\\set ON_ERROR_STOP on
BEGIN;

CREATE TEMP TABLE demo_roster (
    user_id uuid PRIMARY KEY, email text NOT NULL, full_name text NOT NULL,
    preferred_language text NOT NULL, speak_language text NOT NULL, listen_language text NOT NULL
) ON COMMIT DROP;
INSERT INTO demo_roster VALUES
{values};

INSERT INTO auth.users (
    id, email, password_hash, full_name, preferred_language, timezone,
    is_active, is_locked, email_verified, email_verified_at, created_at, updated_at
)
SELECT r.user_id, r.email, {q(PASSWORD_HASH)}, r.full_name, r.preferred_language, 'Asia/Ho_Chi_Minh',
       true, false, true, NOW(), NOW(), NOW()
FROM demo_roster AS r
ON CONFLICT (email) DO UPDATE SET full_name = EXCLUDED.full_name, is_active = true, is_locked = false;

-- An email that already belonged to another account would leave PART 2 pointing at a user id that
-- does not exist. Fail here instead of half-seeding.
DO $$
DECLARE v_conflict text;
BEGIN
    SELECT string_agg(u.email, ', ') INTO v_conflict
    FROM demo_roster AS r JOIN auth.users AS u ON lower(u.email) = lower(r.email)
    WHERE u.id <> r.user_id;
    IF v_conflict IS NOT NULL THEN
        RAISE EXCEPTION 'Email already used by another account: %', v_conflict;
    END IF;
END $$;

INSERT INTO auth.user_settings (
    id, user_id, default_speak_language, default_listen_language,
    voice_clone_enabled, auto_generate_summary, default_max_participants, updated_at
)
SELECT gen_random_uuid(), r.user_id, r.speak_language, r.listen_language, true, true, 10, NOW()
FROM demo_roster AS r
ON CONFLICT (user_id) DO UPDATE SET
    default_speak_language = EXCLUDED.default_speak_language,
    default_listen_language = EXCLUDED.default_listen_language,
    voice_clone_enabled = true, auto_generate_summary = true, updated_at = NOW();

-- Platform role 'user' only: these logins must not reach /api/v1/admin/*.
INSERT INTO auth.user_roles (id, user_id, role_id, assigned_at)
SELECT gen_random_uuid(), r.user_id, sys.id, NOW()
FROM demo_roster AS r CROSS JOIN (SELECT id FROM auth.roles WHERE name = 'user') AS sys
WHERE NOT EXISTS (SELECT 1 FROM auth.user_roles ur WHERE ur.user_id = r.user_id AND ur.role_id = sys.id);

DO $$
DECLARE v int;
BEGIN
    SELECT count(*) INTO v FROM auth.users
    WHERE id::text LIKE '019f2b00-0de0-7000-9300-%' AND is_active AND email_verified;
    IF v <> {len(rows)} THEN RAISE EXCEPTION 'Expected {len(rows)} demo accounts, found %', v; END IF;
END $$;

COMMIT;
"""


def settings_json(domain: str) -> str:
    # Shape read off the live demo workspace on 4 Oct 2026 (PascalCase keys, BARE language codes).
    # AllowedTargetLanguages leaves Korean out on purpose: Flow 2 shows it as "Blocked".
    return f"""jsonb_build_object(
        'DefaultLanguage', 'vi', 'Timezone', 'Asia/Ho_Chi_Minh', 'MaxActiveRooms', 20,
        'ArtifactRetentionDays', 30, 'InvitationExpiryDays', 7, 'VoiceCloningEnabled', true,
        'IsProfanityFilterEnabled', true, 'RestrictLanguages', true, 'AllowAnyPlugins', true,
        'AllowedTargetLanguages', jsonb_build_array('vi', 'en', 'ja'),
        'VerifiedDomains', jsonb_build_array({q(domain)}),
        'AllowExternalCollaboration', true, 'RequireVerifiedDomainForInternal', false,
        'ExternalGracePeriodHours', NULL,
        'AiUsagePolicy', jsonb_build_object(
            'AllowExternalLlm', true, 'UseGlobalGlossary', true,
            'RedactPii', jsonb_build_object('Enabled', true),
            'Dlp', jsonb_build_object('Enabled', true, 'KeywordsBlacklist', jsonb_build_array('Fuck', 'Shit', 'Damn')),
            'TranslationProfile', jsonb_build_object(
                'TranslationTone', 'professional',
                'LanguageSpecificRules', jsonb_build_object(
                    'VietnameseHonorificStyle', 'formal_hierarchical',
                    'JapaneseHonorificStyle', 'keigo_teineigo'))))"""


def workspace_sql(rows: list[dict]) -> str:
    blocks = []
    for w, (key, company, slug, domain, flow) in enumerate(WORKSPACES):
        owner = next(r for r in rows if r["ws"] == w and r["owner"])
        blocks.append(f"""-- {company} ({key}, Flow {flow})
INSERT INTO workspace.workspaces (
    id, name, slug, owner_id, logo_url, allow_external_collaboration,
    require_verified_domain_for_internal, allow_subdomains, settings, is_active,
    created_at, created_by, updated_at, updated_by
) VALUES (
    {q(workspace_id(w))}, {q(company)}, {q(slug)}, {q(owner['user_id'])}, NULL, true, false, false,
    {settings_json(domain)},
    true, NOW(), {q(owner['user_id'])}, NOW(), {q(owner['user_id'])}
)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, slug = EXCLUDED.slug, owner_id = EXCLUDED.owner_id,
    settings = EXCLUDED.settings, is_active = true, deleted_at = NULL, deleted_by = NULL, updated_at = NOW();
""")
    # Flow 1: Owner only. Flow 2: everyone, with their role. Lowercase 'active', capitalised
    # 'Internal' — what the live rows hold. can_create_meetings true: the gate fails closed.
    members = []
    for r in rows:
        if r["flow"] == 1 and not r["owner"]:
            continue
        role = "Owner" if r["owner"] else r["role"]
        members.append(f"    ({q(workspace_id(r['ws']))}, {q(r['user_id'])}, {q(ROLE_IDS[role])})")
    expected = sum(1 for r in rows if r["flow"] == 2 or r["owner"])
    members_sql = ",\n".join(members)
    return f"""-- Demo seed, four companies — PART 2/4: workspace (warptalk_workspace). GENERATED by generate.py.
-- Run PART 1 first. Flow 1 workspaces get their Owner only; Flow 2 workspaces get all nine.
\\set ON_ERROR_STOP on
BEGIN;

{"".join(blocks)}
CREATE TEMP TABLE demo_members (workspace_id uuid, user_id uuid, role_id uuid) ON COMMIT DROP;
INSERT INTO demo_members VALUES
{members_sql};

INSERT INTO workspace.workspace_members (
    id, workspace_id, user_id, role_id, membership_type, status, can_create_meetings, joined_at
)
SELECT gen_random_uuid(), m.workspace_id, m.user_id, m.role_id, 'Internal', 'active', true, NOW()
FROM demo_members AS m
ON CONFLICT (workspace_id, user_id) DO UPDATE SET
    role_id = EXCLUDED.role_id, membership_type = 'Internal', status = 'active',
    can_create_meetings = true, removed_at = NULL, removed_by = NULL;

DO $$
DECLARE v int; v_roles int;
BEGIN
    SELECT count(*) INTO v FROM workspace.workspace_members
    WHERE workspace_id::text LIKE '019f2b00-0de0-7000-9300-%' AND status = 'active' AND removed_at IS NULL;
    IF v <> {expected} THEN RAISE EXCEPTION 'Expected {expected} demo memberships, found %', v; END IF;
    SELECT count(*) INTO v_roles FROM (VALUES {", ".join(f"({q(i)}::uuid)" for i in ROLE_IDS.values())}) AS r(id)
    WHERE r.id IN (SELECT role_id FROM workspace.workspace_members WHERE workspace_id::text LIKE '019f2b00-0de0-7000-9300-%');
    IF v_roles <> 3 THEN RAISE EXCEPTION 'Owner/Admin/Member role ids did not all land; re-check ROLE_IDS'; END IF;
END $$;

COMMIT;
"""


def billing_sql(rows: list[dict]) -> str:
    inserts = []
    for w, (key, company, slug, domain, flow) in enumerate(WORKSPACES):
        owner = next(r for r in rows if r["ws"] == w and r["owner"])
        inserts.append(f"""INSERT INTO subscription.subscriptions (
    id, user_id, workspace_id, plan_id, status, credits_remaining, credits_used_this_cycle,
    overage_credits_this_cycle, current_period_start, current_period_end, auto_renew, is_active,
    service_state, owner_email_domain, billing_contact_email, created_at, created_by, updated_at, updated_by
)
SELECT {q(ID(0xB0 + w + 1))}, {q(owner['user_id'])}, {q(workspace_id(w))}, p.id, 'active', 1400000, 0, 0,
       NOW() - INTERVAL '1 day', NOW() + INTERVAL '30 days', true, true, 'healthy',
       {q(domain)}, {q(owner['email'])}, NOW(), {q(owner['user_id'])}, NOW(), {q(owner['user_id'])}
FROM demo_plan AS p
ON CONFLICT (id) DO UPDATE SET
    plan_id = EXCLUDED.plan_id, status = 'active', is_active = true, service_state = 'healthy',
    credits_remaining = EXCLUDED.credits_remaining, current_period_start = EXCLUDED.current_period_start,
    current_period_end = EXCLUDED.current_period_end, deleted_at = NULL, updated_at = NOW();
""")
    return f"""-- Demo seed, four companies — PART 3/4: billing (warptalk_billing). GENERATED by generate.py.
-- A live subscription per workspace on the `enterprise` plan, the plan the main demo workspace
-- runs on (no longer for sale, still honoured). Without it WT-515's paywall blocks meetings.
-- The entitlement snapshot is NOT written here: EntitlementReconcileWorker republishes it from
-- these rows within its interval (hourly). Never hand-write workspace_entitlement_snapshots.
\\set ON_ERROR_STOP on
BEGIN;

CREATE TEMP TABLE demo_plan AS
SELECT id FROM subscription.plans WHERE slug = 'enterprise' AND deleted_at IS NULL LIMIT 1;
DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM demo_plan) THEN RAISE EXCEPTION 'No enterprise plan'; END IF;
END $$;

{"".join(inserts)}
DO $$
DECLARE v int;
BEGIN
    SELECT count(*) INTO v FROM subscription.subscriptions
    WHERE workspace_id::text LIKE '019f2b00-0de0-7000-9300-%'
      AND is_active AND status = 'active' AND current_period_end >= NOW() AND deleted_at IS NULL;
    IF v <> {len(WORKSPACES)} THEN RAISE EXCEPTION 'Expected {len(WORKSPACES)} live subscriptions, found %', v; END IF;
END $$;

COMMIT;
"""


def glossary_sql(rows: list[dict]) -> str:
    def terms(path: Path) -> list[dict]:
        with path.open(encoding="utf-8") as fh:
            return [r for r in csv.DictReader(fh) if r.get("Term") and r.get("Translation")]

    sources = [("en", "vi", "Thuật ngữ hợp đồng & vận hành (EN→VI)", terms(DEMO_DIR / "glossary-en-vi.csv")),
               ("vi", "en", "Business terms (VI→EN)", terms(DEMO_DIR / "glossary-vi-en.csv"))]
    out = []
    n = 0
    for w, (key, company, slug, domain, flow) in enumerate(WORKSPACES):
        if flow != 2:
            continue  # Flow 1 builds its glossary on stage.
        owner = next(r for r in rows if r["ws"] == w and r["owner"])
        for g, (src, tgt, name, items) in enumerate(sources):
            n += 1
            gid = ID(0xC0 + n)
            out.append(f"""INSERT INTO transcript.glossaries (
    id, workspace_id, name, description, source_language, target_language, term_count, is_active,
    created_at, created_by, updated_at, updated_by
) VALUES ({q(gid)}, {q(workspace_id(w))}, {q(company + " — " + name)},
    {q("Seeded for the demo: the glossary Flow 1 builds.")}, {q(src)}, {q(tgt)}, {len(items)}, true,
    NOW(), {q(owner['user_id'])}, NOW(), {q(owner['user_id'])})
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, term_count = EXCLUDED.term_count,
    is_active = true, deleted_at = NULL, updated_at = NOW();
DELETE FROM transcript.glossary_terms WHERE glossary_id = {q(gid)};
INSERT INTO transcript.glossary_terms (
    id, glossary_id, source_term, target_term, definition, usage_note, domain, priority, is_active,
    created_at, created_by, updated_at, updated_by
) VALUES
""" + ",\n".join(
                f"    (gen_random_uuid(), {q(gid)}, {q(t['Term'])}, {q(t['Translation'])}, {q(t.get('Definition') or None)}, "
                f"{q(t.get('UsageNote') or None)}, 'business', 5, true, NOW(), {q(owner['user_id'])}, NOW(), {q(owner['user_id'])})"
                for t in items
            ) + ";\n")
    return f"""-- Demo seed, four companies — PART 4/4: glossaries (warptalk_transcript). GENERATED by generate.py.
-- Flow 2 workspaces only, from demo/glossary-*.csv. Bare language codes, as the table stores.
\\set ON_ERROR_STOP on
BEGIN;

{"".join(out)}
COMMIT;
"""


def consent_sql(rows: list[dict]) -> str:
    """VOICE_CLONE consent for the Flow 2 accounts, recorded at the owner's request (4 Oct 2026).

    Flow 2 does not demo the consent step, and without a grant the room refuses to clone anyone
    (UserServiceGrpc.HasVoiceCloneConsent reads the LATEST row's status). These are the team's own
    demo logins. The row is what VoiceConsentService.GrantAsync writes, with the CURRENT text
    version, and says in user_agent that a script recorded it. Flow 1 accounts are left alone.
    """
    flow2 = [r for r in rows if r["flow"] == 2]
    values = ",\n".join(f"    ({q(r['user_id'])})" for r in flow2)
    return f"""-- Demo seed, four companies — PART 5/5: voice-clone consent (warptalk_auth). GENERATED.
-- Flow 2 accounts only. Insert a GRANTED row only where the latest row is not already GRANTED.
\\set ON_ERROR_STOP on
BEGIN;

CREATE TEMP TABLE demo_consent_users (user_id uuid PRIMARY KEY) ON COMMIT DROP;
INSERT INTO demo_consent_users VALUES
{values};

INSERT INTO voice.voice_consents (
    id, user_id, voice_profile_id, consent_type, consent_status, consent_text_version,
    granted_at, revoked_at, ip_address, user_agent, created_at
)
SELECT uuidv7(), u.user_id, NULL, 'VOICE_CLONE', 'GRANTED', '{VOICE_CONSENT_VERSION}',
       NOW(), NULL, NULL, 'seed: demo prep, recorded at the workspace owner''s request', NOW()
FROM demo_consent_users AS u
WHERE COALESCE((
    SELECT c.consent_status FROM voice.voice_consents AS c
    WHERE c.user_id = u.user_id AND c.consent_type = 'VOICE_CLONE'
    ORDER BY c.created_at DESC LIMIT 1
), '') <> 'GRANTED';

DO $$
DECLARE v int;
BEGIN
    SELECT count(*) INTO v FROM demo_consent_users AS u
    WHERE (SELECT c.consent_status FROM voice.voice_consents AS c
           WHERE c.user_id = u.user_id AND c.consent_type = 'VOICE_CLONE'
           ORDER BY c.created_at DESC LIMIT 1) = 'GRANTED';
    IF v <> {len(flow2)} THEN RAISE EXCEPTION 'Expected {len(flow2)} granted, found %', v; END IF;
END $$;

COMMIT;
"""


def main() -> None:
    rows = roster()
    files = {
        "01-auth.sql": auth_sql(rows),
        "02-workspace.sql": workspace_sql(rows),
        "03-billing.sql": billing_sql(rows),
        "04-glossary.sql": glossary_sql(rows),
        "05-voice-consent.sql": consent_sql(rows),
    }
    for name, sql in files.items():
        (HERE / name).write_text(sql, encoding="utf-8")
    lines = ["| Workspace | Flow | Email | Name | Role in workspace |", "|---|---|---|---|---|"]
    for r in rows:
        status = r["role"] if r["flow"] == 2 or r["owner"] else "not invited"
        if r["owner"]:
            status = "Owner"
        lines.append(f"| {r['company']} | {r['flow']} | `{r['email']}` | {r['name']} | {status} |")
    (HERE / "ROSTER.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
    print("wrote", ", ".join(files), "and ROSTER.md")


if __name__ == "__main__":
    main()
