#!/bin/sh
set -eu

database=""
output=""
while [ "$#" -gt 0 ]; do
  case "$1" in
    -d) database="$2"; shift 2 ;;
    -f) output="$2"; shift 2 ;;
    *) shift ;;
  esac
done

if [ "$database" = "${FAIL_DATABASE:-}" ]; then
  echo "simulated pg_dump failure for $database" >&2
  exit 42
fi

: > "$output"
