deployment:
  replicas: 1
logs:
  general:
    level: DEBUG
  access:
    enabled: true
ports:
  web:
    port: 8000
    hostPort: 80
    expose:
      default: true
    exposedPort: 80
  websecure:
    port: 8443
    hostPort: 443
    expose:
      default: true
    exposedPort: 443
tlsStore:
  default:
    defaultCertificate:
      secretName: warptalk-tls
podDisruptionBudget:
  enabled: true
  minAvailable: 1
service:
  type: LoadBalancer
  spec:
    externalTrafficPolicy: Cluster
autoscaling:
  enabled: false
affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          topologyKey: kubernetes.io/hostname
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: traefik
